Add local2global conversion in drift and identity passmethods
lnls-fac/trackcpp pull request #57
Opened 2022-12-13 21:09 UTC by xresende

i noticed we are not using `t_in`, `t_out`, `r_in` and `r_out` in drift and identity passmethods. this came as a surprise for me when i tried to generate orbit signatures of dipolar perturbations at the center of straight sections (for IDs). sometimes it is usefull to be able to do such thing, like adding dipolar perturbations at ring locations with such elements (center of straight sections as I did, or at BPMs, etc), but most of the time it is represents trivial and useless calculations. 

should we use it ?

i measured the additional cost of such calculations in our current SI model:

```Python3
import time
import numpy as np
import pyaccel
from pymodels import si

def tracking(nrparts, nrturns):
    m = si.create_accelerator()
    particles = np.zeros((6, nrparts))
    t0 = time.time()
    pyaccel.tracking.ring_pass(m, particles, nrturns)
    t1 = time.time()
    print(f'time {t1-t0:.3f} s')
    
# before PR
%timeit tracking(1, 5000)
time 6.737 s
time 6.739 s
time 6.648 s
time 6.595 s
time 6.681 s
time 6.601 s
time 6.686 s
time 6.611 s
6.98 s ± 51.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

# after PR
%timeit tracking(1, 5000)
time 6.992 s
time 6.973 s
time 7.123 s
time 6.976 s
time 6.951 s
time 6.962 s
time 7.115 s
time 6.965 s
7.33 s ± 69.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

```

2022-12-16 11:25 UTC, fernandohds564 commented
@xresende, I don't understand how this PR can change the execution times of the code in the description, because it only adds a new `pass_method`, inexistent in the default sirius model. Does it increase the execution times just because of the existence of the new `pass_method`?

Another point is that I think this new `pass_method` should not be a drift with the `global2local` transformations taken into account. I think it could just be a pure transformation of the beam coordinates, with a more appropriate name. What do you think?

2022-12-16 11:26 UTC, fernandohds564 requested changes
comments in the main thread.

2022-12-16 13:13 UTC, xresende commented
> @xresende, I don't understand how this PR can change the execution times of the code in the description, because it only adds a new `pass_method`, inexistent in the default sirius model. Does it increase the execution times just because of the existence of the new `pass_method`?
> 
> Another point is that I think this new `pass_method` should not be a drift with the `global2local` transformations taken into account. I think it could just be a pure transformation of the beam coordinates, with a more appropriate name. What do you think?

@fernandohds564 , as I discussed with you outside github, this PR is a mixture of two possible options: adding g2l back-and-forth transformations in identity and drift passmethods (implemented here!) or adding a new passmethod drift_g2l (also implemented here). I opened this PR so that you guys can answer my posed question: which one is better to keep ?

the time estimates were evaluated using standard drift and identify passmethds with additional g2l and l2g conversions, (as is coded here!), so they do influence the tracking times.... I am confused with you questioning...

regarding you second point: I think we may want to add a coordinate shift or/and rotation in elements that now are drifts in our models. having the possibility of doing this in drifts is the most practical way: avoid changing the model just for adding such transformations in drifts but only changing the passmethod index of the element. also, these drift_g2l pass methods can be used for markers replacement too since de dafult lenght=0 is used and generate and identity passmethod in pracice. But if computation cost of using a drift(length=0) for markers is to be avoided, we can also add a second new passmethod: one for drift with g2l_transf, another for marker with g2l_transf...

the name `drift_g2l` i did not like either, but opened the PR anyways so that you guys can make suggestions. maybe we can change to another thing. `g2ltransf` (`g2ltransf_drift` and `g2ltransf_marker` in case of separate new passmethods) or similar?

2023-01-13 19:29 UTC, fernandohds564 approved these changes

2023-01-13 19:41 UTC, murilobalves approved these changes

2023-01-23 14:12 UTC, RafaelLyra8 approved these changes

2023-01-30 11:34 UTC, murilobalves approved these changes

2023-01-30 12:01 UTC, fernandohds564 approved these changes

2023-01-30 14:36 UTC, anacso17 approved these changes

2023-01-30 19:41 UTC, Gabrielrezende-asc approved these changes

2023-01-30 20:00 UTC, RafaelLyra8 approved these changes

2023-01-31 02:04 UTC, merged