Export std::vector memory address pointer to python
lnls-fac/trackcpp pull request #70
Opened 2024-04-26 18:07 UTC by VitorSouzaLNLS

This change makes it possible for PyAccel to access the Elements polynomials without copying data.

2024-04-27 13:13 UTC, fernandohds564 approved these changes

2024-04-29 12:17 UTC, murilobalves approved these changes

2024-05-03 11:46 UTC, xresende approved these changes

2024-05-03 12:22 UTC, xresende commented
@VitorSouzaLNLS , I think it is useful the option for he classes to return signatures in all elements positions, not only at BPMs. Sometimes we are interested in the vertical dispersion function inside the dipoles for calculating beam sizes, for example.

2024-05-03 12:23 UTC, xresende requested changes
See comment

2024-05-03 16:42 UTC, xresende approved these changes

2024-05-23 19:08 UTC, vellosok75 approved these changes

2024-06-03 13:30 UTC, merged